CREATE TABLE Producti(
ID INT PRIMARY KEY NOT NULL,
IME_NA_PRODUCT VARCHAR(50)NOT NULL,
KATEGORIJA VARCHAR(40)NOT NULL,
CENA_DOSTAVKA INT NOT NULL,
KOLICINA_ZALIHA INT NOT NULL,
PREKINATI_PRODAZBI INT NOT NULL,
KOLICINA_ZA_KRITICNA_ZALIHA INT NOT NULL,
DOSTAVUVAC VARCHAR(30)  NOT NULL,

);
CREATE TABLE Prodavnici(
ID INT PRIMARY KEY NOT NULL,
IME VARCHAR(50) NOT NULL,
ADRESA VARCHAR(40) NOT NULL,
GRAD VARCHAR(20) NOT NULL,
TELEFONSKI_BROJ INT NOT NULL,
FAKS VARCHAR(20) NOT NULL,
MAIL VARCHAR(20) NOT NULL,
WEB_ADRESA VARCHAR(50) NOT NULL
);
CREATE TABLE Sluziteli(
ID INT PRIMARY KEY NOT NULL,
IME VARCHAR(25) NOT NULL,
PREZIME VARCHAR(25) NOT NULL,
DOLZNOST VARCHAR(25) NOT NULL,
EGN VARCHAR(25) NOT NULL,
DATA_VLEZ INT NOT NULL,
DATA_IZLEZ INT NOT NULL,
TELEFONSKI_BROJ INT NOT NULL,
ADRESA VARCHAR(30) NOT NULL,
GRAD VARCHAR(21)NOT NULL,
MAIL VARCHAR(40)NOT NULL
);
CREATE TABLE Dostavuvaci(
ID INT PRIMARY KEY NOT NULL,
IME_FIRMA VARCHAR(50) NOT NULL,
IME_KONTAKT_LICE VARCHAR(50) NOT NULL,
DOLZNOST_KONTAKT_LICE VARCHAR(40) NOT NULL,
ADRESA VARCHAR(50) NOT NULL,
TELEFONSKI_BROJ INT,
FAKS VARCHAR(40) NOT NULL,
MAIL VARCHAR(20) NOT NULL,
WEB_ADRESA VARCHAR(40)NOT NULL,
);


